phases:
  build:
    base: ubuntu:18.04
    target: [dev]
    environment:
      DEBIAN_FRONTEND: "noninteractive"
    workdir: /app
    commands:
      - apt-get update
      - echo y | apt-get install locales
      - echo y | apt install build-essential
      - apt -qq install -y --no-install-recommends curl git gnupg2 wget
      - |
        set -ex; \
        apt-get update && apt-get install -y --no-install-recommends busybox git python3 python3-dev \
        python3-pip python3-lxml pv; \
        apt-get autoclean; \
        apt-get autoremove; \
        rm -rf /var/lib/apt/lists/*
      - pip3 install setuptools wheel yarl multidict
      - copy: requirements.txt .
      - pip3 install -r requirements.txt
      - dpkg-reconfigure locales
      - copy: . /app
    tags:
      - my-container-tag
      - production

cmd: ["python3", "Merisa"]
